version: '3'

services:
  backend:
    ports:
      - 5000:5000
    build: 
      context: ~/code/Devopswithdocker/part1/exer1.11
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=boot
      - DB_NAME=db1
      - DB_HOST=postgres
  frontend:
    ports:
      - 8000:8000
    build: 
      context: ~/code/Devopswithdocker/part1/exer1.10
      args:
        API_URL: '/api'
    environment: 
      - API_URL=http://localhost:8080
  redis:
    image: redis
  norsu:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boot
      - POSTGRES_DB=db1
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data: