version: '3'
        
services:
        backend:
                ports:
                - 5000:5000
                build: ~/code/Devopswithdocker/part1/exer1.11
        frontend:
                ports:
                - 8000:8000
                build: ~/code/Devopswithdocker/part1/exer1.10

