version: '3'

services:
        backend:
                ports:
                        - 5000:5000
                build: ~/code/Devopswithdocker/part1/exer1.11
                environment:
                        - REDIS=redis
                        - DB_USERNAME=postgres
                        - DB_PASSWORD=boot
                        - DB_NAME=postgres
                        - DB_HOST=db1
                depends_on:
                        - norsu
        frontend:
                ports:
                        - 8000:8000
                build: ~/code/Devopswithdocker/part1/exer1.10
        redis:
                image: redis
                ports:
                        - 6379:6379
        norsu:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: boot


